---
apiVersion: v1
kind: Secret
metadata:
  name: test-blue-green
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: ""
  password: ""
  username: ""
---