---
apiVersion: v1
kind: Secret
metadata:
  name: test-blue-green
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: "" # Put Repo
  password: "" # Token or password from repo
  username: "" # User from Repo
---