---
apiVersion: v1
kind: Service
metadata:
  name: my-app-blue
spec:
  selector:
    app: my-app
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-green
spec:
  selector:
    app: my-app
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
    version: blue  # 🔄 Alternamos entre 'blue' e 'green'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
  type: NodePort  # Expor o serviço na nuvem ou NodePort se local
