---
apiVersion: v1
kind: Service
metadata:
  name: my-app-blue
spec:
  selector:
    app: my-app
    version: blue
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
---