replicaCount: 2

image:
  repository: stefanprodan/podinfo
  tagBlue: "blue"
  tagGreen: "green"
  pullPolicy: IfNotPresent

deployment:
  activeVersion: blue  # 🔄 Alterna entre 'blue' e 'green'

service:
  type: NodePort  # Pode ser NodePort também
  port: 8000
  targetPort: 9898
